### ISSUE TITLE
Adding Custom Fields to Interface

### ISSUE THREAD

**Issue by scotthardwick** [ndunand/moodle-enrol_attributes#1]
Hi!
Great plugin and VERY useful !!!
Is there a way to add site specific custom fields 

For example:
{ label: "DegreeProgram", value: "program" },
{ label: "Classification", value: "classification" },

to the interface without hand editing the jquery.booleanEditor.js file?
If not, could I request that such a feature be added?  
Thanks!
Scott

**Comment by Kathrin84** [comment]
I would also appreciate if custom fields could be added to the plugin.

Maybe I also did something wrong, so it was my fault that it did not work out.
I wanted to add a profile filed called 'studiengang' (course of studies).
So I added it to the field Mappings in that way:
Studiengang:studiengang (Label:profile_field).
I also tried "Studiengang":"studiengang" and vice versa (studiengang:Studiengang)
Unfortunately, none of it has any affect to the dropdown list. 

Regards!
Kathrin

**Comment by tyi-dvelopit** [comment]
I was looking for a way to add custom profile fields as there should be a way to add my own custom fields to the dropdown box but based upon the comments above it seems it does not (yet) support it even after more than half a year. Is the plugin going to get the update at all to allow custom profile fields being pulled in?

**Comment by ndunand** [comment]
Hello all and thanks for your comments. I just made some changes that – I hope – will make this plugin more useful and more flexible. Please try the new version and tell me if this addresses your issues.

**Comment by Kathrin84** [comment]
Hi and thanks for your development. The selecting of the custom profile fields is very comfortable now. However I don't get it to work.
I made a new custom profile field called 'isTeacher' which is a checkbox. If the user is a teacher in any other course, I checked the checkbox for test users. Then I selected that custom profile field in your plugin and checked it against the values (one after another) 1, true, TRUE and checked. However, nothing had an impact on the enrolment of users into the course. I logged in with a user that had this checked checkbox and also used the force enrolment button. I don't have any clue against what value I should check the field that it works.

Greets
Kathrin

**Comment by ndunand** [comment]
Hi Katrin,
Could you check this against fields containing text values, see if the enrolments work, and report back?

**Comment by Kathrin84** [comment]
Hi,

this was the first thing I tried. We have a custom profile field called program of studies and in a course I used your plugin and checked it against the String Biologie (this is how it is stored in the database):
![check_against_text](https://cloud.githubusercontent.com/assets/4711883/11062598/776ed12e-87b0-11e5-98dc-f848bb64d28e.png)

Then I took a user that has this specific program of studies:
![user_detail](https://cloud.githubusercontent.com/assets/4711883/11062602/7f2bdccc-87b0-11e5-83db-a8ae33c6fdbc.png)

And I logged in with this user account (as it is a test user I can use):
![user_login](https://cloud.githubusercontent.com/assets/4711883/11062605/855c923a-87b0-11e5-878f-70a177bb8b1e.png)

As nothing happend, I additionally used the Force enrolments button... wiithout any success. Still no additional user in the course... :(

**Comment by ndunand** [comment]
Hello,

Sorry about the delay. It appears there was at least one bug in the code regarding field names. Could you whether the field name ("short name") has capital letters in it?

**Comment by Kathrin84** [comment]
The shortname of the custom profile field is all lower case:
![shortname](https://cloud.githubusercontent.com/assets/4711883/11177052/ebd11ffe-8c42-11e5-9759-f3679d05e982.png)

**Comment by ndunand** [comment]
Thanks. Could you replace the "DEBUGGING" block at the bottom of `enrol/attributes/edit.php` with the following?

```
// DEBUGGING : BEGIN
debugging('customtext1= '.print_r(json_decode($instance->customtext1), true), DEBUG_DEVELOPER);
$debug_fieldsandrules = enrol_attributes_plugin::attrsyntax_toarray($instance->customtext1);
debugging('fieldsandrules= '.print_r($debug_fieldsandrules, true), DEBUG_DEVELOPER);
$debug_arraysql = enrol_attributes_plugin::arraysyntax_tosql($debug_fieldsandrules);
debugging('arraysql= '.print_r($debug_arraysql, true), DEBUG_DEVELOPER);
$debug_sqlquery = 'SELECT DISTINCT u.id FROM mdl_user u '.$debug_arraysql['select'] . ' WHERE ' . $debug_arraysql['where'];
debugging('sqlquery= '.print_r($debug_sqlquery, true), DEBUG_DEVELOPER);
$debug_users = $DB->get_records_sql($debug_sqlquery);
debugging('countusers= '.print_r(count($debug_users), true), DEBUG_DEVELOPER);
// DEBUGGING : END
```

Then, enable Developer mode on your Moodle, go and edit the rule and please paste back the resulting debugging code.

**Comment by Kathrin84** [comment]
Here's the result. There's an error while reading from the database.
![debugging](https://cloud.githubusercontent.com/assets/4711883/11177554/a3c45a60-8c46-11e5-9777-2f91f27f9e31.png)

**Comment by ndunand** [comment]
Thanks. Could you check your `enrol/attributes/lib.php` file is the same as the latest one here ( https://github.com/ndunand/moodle-enrol_attributes/blob/master/lib.php#L168 ), lines 168-171?

**Comment by Kathrin84** [comment]
Hi, I've updated your plugin to the newest version and now it's working when users that meet the criteria are logging in. I also tested it with checkbox profile fields and checked them against 1 (thats the value stored in the database) with success.
The force...  button still seem to do nothing, but the functionality itself is given. 
Thanks for your work!

**Comment by ndunand** [comment]
Hello, and thanks again for your feedback.

That's already much better! The "Force" feature has to be improved, especially since there is not much feedback to the user. It can take some time (after confirming) until an alert box comes back saying "OK [...] `x` users have been enrolled", where `x` can be any number or zero. There can be a long delay if rules are complex or if there are tens or hundreds of thousands of users registered in your Moodle.

Does it report back zero users having been enrolled, or is just nothing being displayed?

**Comment by ndunand** [comment]
By the way, I'm just waiting for some more feedback from another user before releasing an official new version, which will be posted on Moodle.org. I hope it'll be done within a day or two.

**Comment by Kathrin84** [comment]
Hi Nico,
I've tried the force button with a result of 4 users. They should be enroled very fast. As nothing happend, I had a look at the browser console and saw this error:
![force](https://cloud.githubusercontent.com/assets/4711883/11205064/df7444f8-8d04-11e5-8443-027396b49c5c.png)

The file exists on our server:
![filetree](https://cloud.githubusercontent.com/assets/4711883/11205078/0482ad84-8d05-11e5-91d0-84a8a5ad8875.png)

I don't know why the system says that it cannot find the force.php file...

Cheers,
Kathrin

**Comment by ndunand** [comment]
Hello Kathrin,

Could you activate debugging mode on your Moodle, then go to the edit screen of the enrolment method (where the Force button does not work), and post back the debugging messages here?

**Comment by Kathrin84** [comment]
Hi,

in this system where I do my testing, debugging is always on.
These are the only messages I get and they are from your edit.php debugging messages:

customtext1= stdClass Object ( [rules] => Array ( [0] => stdClass Object ( [param] => isDozent [value] => 1 ) ) )
line 94 of /enrol/attributes/edit.php: call to debugging()
fieldsandrules= Array ( [customuserfields] => Array ( [1] => studiengang [2] => abteilung [3] => fachbereich [6] => isstudent [5] => isemployee [7] => isDozent ) [rules] => Array ( [0] => stdClass Object ( [param] => isDozent [value] => 1 ) ) )
line 96 of /enrol/attributes/edit.php: call to debugging()
arraysql= Array ( [select] => RIGHT JOIN mdl_user_info_data d1 ON d1.userid = u.id [where] => (d1.fieldid = 7 AND ( d1.data = '1' OR d1.data LIKE '%;1' OR d1.data LIKE '1;%' OR d1.data LIKE '%;1;%' )) )
line 98 of /enrol/attributes/edit.php: call to debugging()
sqlquery= SELECT DISTINCT u.id FROM mdl_user u RIGHT JOIN mdl_user_info_data d1 ON d1.userid = u.id WHERE (d1.fieldid = 7 AND ( d1.data = '1' OR d1.data LIKE '%;1' OR d1.data LIKE '1;%' OR d1.data LIKE '%;1;%' ))
line 100 of /enrol/attributes/edit.php: call to debugging()
countusers= 4
line 102 of /enrol/attributes/edit.php: call to debugging()

**Comment by ndunand** [comment]
Thanks.
So this correctly reports that DB queries are OK and that 4 users should be enrolled.
As for the force.php, the browser incorrectly reports a 404 error (= missing ressource) because the force.php file yields an error. Does your browser debugger allow you to see the contents (errors & debugging messages) generated by the force.php file ?

**Comment by Kathrin84** [comment]
Yes, the queries are okay now and when a user manually logs in, this user that meets the criteria is enrolled correctly into the course.

Honestly, I do not exactly know how to make my browser give out errors for a file he cannot find. Do you know what settings I have to do in the browser to make this possible? I can use Safari, Chrome or Firefox.

**Comment by ndunand** [comment]
Easier, please add the following code at the end of the DEBUGGING code in the enrol/attributes/edit.php file.

```
debugging('force.php DEBUGGING:', DEBUG_DEVELOPER);
if ($instanceid) {
    $nbenrolled = enrol_attributes_plugin::process_enrolments(null, $instanceid);
    debugging('nbenrolled= '.print_r($nbenrolled, true), DEBUG_DEVELOPER);
}
```

Then, go to the rule editing page, use the Purge button (wait for confirmation), then reload the page and post back.

**Comment by Kathrin84** [comment]
Okay, I've done it. Here are only the new debugging messages under countusers = 4:

force.php DEBUGGING:
line 103 of /enrol/attributes/edit.php: call to debugging()
Fehler beim Lesen der Datenbank
Weitere Informationen über diesen Fehler
Debug info: ERROR: argument of AND must be type boolean, not type integer
LINE 1: ...N mdl_user_info_data d2 ON d2.userid = u.id WHERE 1 AND u.de...
^
SELECT DISTINCT u.id FROM mdl_user u RIGHT JOIN mdl_user_info_data d2 ON d2.userid = u.id WHERE 1 AND u.deleted=0 AND (d2.fieldid = 7 AND ( d2.data = '1' OR d2.data LIKE '%;1' OR d2.data LIKE '1;%' OR d2.data LIKE '%;1;%' ))
[array (
)]
Error code: dmlreadexception
Stack trace:
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 291 of /enrol/attributes/lib.php: call to pgsql_native_moodle_database->get_records_sql()
line 105 of /enrol/attributes/edit.php: call to enrol_attributes_plugin::process_enrolments()

**Comment by ndunand** [comment]
Thanks ! It seems Postgres has some minor differences with MySQL that I hadn't expected. In particular, I can't use `WHERE 1` in Postgres.
So, could you replace `' WHERE 1'` by `' WHERE true'` in `enrol/attributes/lib.php` (**mind the space**), line 285 and post back?

**Comment by Kathrin84** [comment]
Hey Nico.
now it's working fine! Forcing the enrollment and purging works!
Thanks for your effort!

Only one little aspect could be optimized. When the procedure of the forced enrollments is done it says:
OK, 0 users have benn enrolled
The 0 is confusing. The correct number should appear (in my case: 4 users have been enrolled).

**Comment by ndunand** [comment]
Perfect, thanks again for your feedback and perseverance.

**Comment by ndunand** [comment]
...and yes, I'll correct that small misbehavior too

**Comment by Kathrin84** [comment]
Thanks for your work and you're welcome. :)
