### ISSUE TITLE
Shibboleth should be optional

### ISSUE THREAD

**Issue by tyi-dvelopit** [ndunand/moodle-enrol_attributes#2]
I think this plugin has more potential if you do not restrict its use only on shibboleth authentication. Maybe it could be optional?

For people who want this plugin to be used on other than Shibboleth, just disabled(commented out) that checking (SCRIPT_NAME) in process_login(...) method which is triggered on user_loggedin event from lib.php

It seems unfortunately for now at lease you need to hard-code into javascript file for those custom fields to use.

**Comment by ndunand** [comment]
Thanks for the feedback – indeed you're right. I just made some modifications that should address all your concerns.

I'd be glad to hear back from you about this.

**Comment by ndunand** [comment]
mainly related to commits 09e4b6a and a3e14ce
