### ISSUE TITLE
The plugin does not work on win10

### ISSUE THREAD

**Issue by IamLuksha** [ndunand/moodle-enrol_attributes#23]
Hello!
Plugin very cool and we like it.
But there is a problem when you go from a computer to Win10 and want to write users to the course, it gives an error.
In the logs it refers to 128 and 149 lines of code in the lib.hph of this plugin

![image](https://user-images.githubusercontent.com/18416207/43511759-ef09128a-9581-11e8-9722-27f96c5f9bbf.png)

**Comment by ndunand** [comment]
Hello,

Thanks for providing feedback !

I'm not sure to understand correctly, could you provide step-by-step instructions on how to reproduce this error?

**Comment by IamLuksha** [comment]
Hello,
On win7 and Linux everything works.
On win10 and MacOS does not work.

https://youtu.be/HANVPPG8ZS0

**Comment by ndunand** [comment]
Thank you. Can you check the browser console for JavaScript errors?

**Comment by IamLuksha** [comment]
![image](https://user-images.githubusercontent.com/18416207/43641446-5e32257e-972c-11e8-829b-ea83d1075131.png)

**Comment by ndunand** [comment]
Alright ... what if you modify the `jquery.booleanEditor.js` file as follows:

<img width="515" alt="screen shot 2018-08-03 at 14 07 52" src="https://user-images.githubusercontent.com/762972/43642165-bc8ac4ce-9726-11e8-991d-36b4523f535f.png">

does it solve the problem?

**Comment by IamLuksha** [comment]
Yes. now works.
If more problems are found, write here.
Thank you so much

**Comment by ndunand** [comment]
Thanks for reporting back, I'll push a new release including this fix.
