### ISSUE TITLE
add condition/delete condition not displaying properly

### ISSUE THREAD

**Issue by sodafiremedia** [ndunand/moodle-enrol_attributes#24]
Hi there, 

So far, your plugin in fantastic! Thank you for writing this!

Two things, in both Chrome and Firefox, the "add condition/delete condition" buttons don't seem to be displaying properly. 
![capture](https://user-images.githubusercontent.com/16257141/44168083-3c760300-a08d-11e8-94e9-8c76416f441b.JPG)

theme is Tikli - which may be the old theme that is causing the problem. 
Also, in another LMS I have with the Lambda theme, the "delete condition" was not working. 

Thank you!

**Comment by ndunand** [comment]
Hello,
Thanks for reporting this and sorry about the delay. Our testing show this works as expected, so closing now.
