### ISSUE TITLE
Do not work nested queries

### ISSUE THREAD

**Issue by IamLuksha** [ndunand/moodle-enrol_attributes#26]
For example, it is necessary to enroll students of 2 courses(курс) of study of 2 and 8 groups(группа).
![image](https://user-images.githubusercontent.com/18416207/45608889-f16d5800-ba5d-11e8-8be5-a4d9f058e828.png)

But so enrollment does not happen.

Even so
![image](https://user-images.githubusercontent.com/18416207/45608923-224d8d00-ba5e-11e8-870e-feabb25ada92.png)

As a result, only such a query works.
![image](https://user-images.githubusercontent.com/18416207/45608969-5aed6680-ba5e-11e8-9101-f5fe6c81f977.png)

Moodle 3.5.1 (Build: 20180709)
postgresql-9.4.18-1
Windows server 2012

**Comment by ndunand** [comment]
Do you have any debugging information? Once the rule is saved go back to editing the rule and it should show something as below, several lines, beginning with `customtext` and ending with `countusers=...`:

<img width="567" alt="screen shot 2018-09-18 at 13 36 59" src="https://user-images.githubusercontent.com/762972/45685056-73d24680-bb48-11e8-810d-ad9ff4854cc3.png">

**Comment by IamLuksha** [comment]
![image](https://user-images.githubusercontent.com/18416207/45686735-afbfd880-bb55-11e8-8090-214cdedda7ba.png)

**Comment by ndunand** [comment]
So this works, it clearly states (`countusers=2`) that this rule matches 2 users.

What about the rules that don't work?

**Comment by IamLuksha** [comment]
I agree that users comply with the rule. But they do not enroll.

![image](https://user-images.githubusercontent.com/18416207/45705309-ec092e00-bb81-11e8-886f-b634d1a1512f.png)

![image](https://user-images.githubusercontent.com/18416207/45705340-004d2b00-bb82-11e8-9221-2ab21437fc2d.png)

**Comment by ndunand** [comment]
Which version of the plugin are you using?

**Comment by IamLuksha** [comment]
I have two sites. One updated on Monday.
On the other one, from this commit https://github.com/ndunand/moodle-enrol_attributes/issues/23

On both shows version 2018080300
And on both does not work.

**Comment by ndunand** [comment]
Indeed, I finally pinpointed it, thanks for reporting it.

This is now fixed in the latest release (2018092000), can you confirm?

**Comment by IamLuksha** [comment]
Yes!!
He is working now!
Thank you very much!

**Comment by ndunand** [comment]
Great, thanks for reporting back.
