### ISSUE TITLE
Typos in lang/en/enrol_attributes.php

### ISSUE THREAD

**Issue by jb-fol** [ndunand/moodle-enrol_attributes#3]
Just noticed a couple of small typos:

line 35
$string['ajax-okforced'] = 'OK, {$a} users have **benn** enrolled';
- should be **been enrolled**

line 41
$string['mappings_desc'] = 'When using Shibboleth **authentification**, this plugin can automatically update a user\'s profile upon each login.<br><br>For instance, if you want to update the user\'s <code>homeorganizationtype</code> profile field with the Shibboleth attribute <code>Shib-HomeOrganizationType</code> (provided that is the environment variable available to the server during login), you can enter on one line: <code>Shib-HomeOrganizationType:homeorganizationtype</code><br>You may enter as many lines as needed.<br><br>To not use this feature or if you don\'t use Shibboleth **authentification**, simple leave this empty.';
- should be **authentication**

**Comment by ndunand** [comment]
Thanks! I just corrected this in bb01092.
