### ISSUE TITLE
Restoring course does not restore this enrollment method

### ISSUE THREAD

**Issue by jonathanjoegit** [ndunand/moodle-enrol_attributes#31]
In a Moodle 3.6.5 platform.

We are using "enrol_attributes" and we want to duplicate courses :

- backup with every data (users, sections, ...)
- restore with everything (enrolment method too)
- We can see only the basic enrolment method... But not this additional plugin.

Any clue ?

Thank you :)

**Comment by ndunand** [comment]
Bonjour Jonathan,

I just fixed this in the latest release, available immediately.

This is the relevant code if interested : https://github.com/ndunand/moodle-enrol_attributes/blob/master/lib.php#L380 

The good news is that your course backups all contain the needed information, just the new version of the plugin is need to restore the enrolment method from the backup.

**Comment by jonathanjoegit** [comment]
Bonjour :)

Perfect, thanks a lot !
