### ISSUE TITLE
Strings missing in AMOS

### ISSUE THREAD

**Issue by dinism** [ndunand/moodle-enrol_attributes#32]
Thanks for the plugin.
I'm a PT-PT translator.
Strange but this strings are missing in AMOS but they are in lang file
![imagem](https://user-images.githubusercontent.com/14828021/101521322-9ba66280-397d-11eb-8b65-53611a412d0f.png)
**In my Moodle:**
![imagem](https://user-images.githubusercontent.com/14828021/101521393-b4af1380-397d-11eb-9f38-99e1bf09dcf5.png)
**AMOS**
![imagem](https://user-images.githubusercontent.com/14828021/101522388-0906c300-397f-11eb-92e6-553f8b49d2aa.png)

**Comment by ndunand** [comment]
Thanks for reporting this issue @dinism , I am looking into the issue with David Mudrák and will let you know. This seems to be related to AMOS and I have created https://tracker.moodle.org/browse/MDLSITE-6368 to this effect.

**Comment by ndunand** [comment]
Hello @dinism , could you please check AMOS again? This has just been fixed, the missing strings are now available for translation.

**Comment by dinism** [comment]
@ndunand **YES, THEY are in AMOS.**
![imagem](https://user-images.githubusercontent.com/14828021/101670530-30c35d00-3a4b-11eb-999c-046f2a40a127.png)

**100% translated to PT-PT. Thanks for the plugin.**
![imagem](https://user-images.githubusercontent.com/14828021/101670591-42a50000-3a4b-11eb-9a41-30d2c221ad5d.png)

**Comment by ndunand** [comment]
Great, thanks for your feedback and for having translated the plugin into Portuguese
