### ISSUE TITLE
Installation folder MUST be called enrol/attributes

### ISSUE THREAD

**Issue by deligant** [ndunand/moodle-enrol_attributes#36]
In the release notes (https://moodle.org/plugins/enrol_attributes/2.9.1-for-moodle-3.5-3.11-build-2021063000/24579) it is stated that you can give any name to the plugin folder, important is it is in the enrol folder.
![image](https://user-images.githubusercontent.com/6317497/125657611-b28cd952-2775-4200-ab0d-4f5ac3870bf7.png)

This is **not true**, because the first step in settings.php is to call a 
`require_once $CFG->dirroot . '/enrol/attributes/locallib.php';`
I suggest to use a more useful
`require_once __DIR__. '/locallib.php';`

or even better define a config file that defines the correct path for the plugin.

At the moment, the only way to make this plugin work is to call the plugin folder "attributes".

**Comment by ndunand** [comment]
Hi,

No, that is a general information displayed by moodle.org's plugins database, not this plugin.

It does _not_ state that you can give the directory any name, only that you should move the directory (whatever its name) into the 'enrol' subdirectory of your Moodle installation.
