### ISSUE TITLE
View/edit rules page doesn't work well when there are hundreds of rules

### ISSUE THREAD

**Issue by jhutch1** [ndunand/moodle-enrol_attributes#40]
We have a Moodle with about 400 rules which assign users to cohorts based on their job role and the physical location in which they work. Unfortunately, this means the view/edit rules page of the plugin is enormous, and it's a struggle to load and use it.

It might be worth adding some pagination to the view/edit rules page (maybe 50 rules per page by default?) for use cases like this.

**Comment by ndunand** [comment]
Apart from display hurdles like the ones you mention, I would think so many rules must have a huge performance impact... is that not the case?

**Comment by jhutch1** [comment]
It probably does. The Moodle only sees about a hundred logins a day though, so even if each user is "heavier" than normal, the server's able to handle it fine.

**Comment by ndunand** [comment]
okay. Could you send a screenshot of the issue? I want to make sure I understand it correctly.

Make sure you blank out any personal information.

**Comment by jhutch1** [comment]
Hmm, hard to do since the list of rules doesn't fit on a single screen. Since there are 400 rules and Moodle is trying to show them all at once, you end up with an extremely long list of rules on the /local/profilecohort/index.php?action=view screen.

**Comment by ndunand** [comment]
Alright, then this is not related to my module (enrol_attributes) but to this module : https://moodle.org/plugins/local_profilecohort from Ulm University.
