### ISSUE TITLE
Issue in build 2021100800 - Moodle 3.9 - PHP7.2 mysql Enrol by user profile field is broken when saving! 

### ISSUE THREAD

**Issue by gemguardian** [ndunand/moodle-enrol_attributes#41]
Hi @ndunand 
Since the change of 11 days ago the Enrol by User profile fields is broken in my learning enviroments. Since the plugin update,  it does not save my settings in the enrolment methode anymore. 

I created a video to show including the debug information. You can see it over here: https://vimeo.com/653610615/54b7d41653

Since I am not a programmer I am not able to fix the issue. So I am hoping you have time to look at it. Especially since I doubt I am the only one having this issue at the moment. 

**DEBUG INFORMATION when saving**
Warning: Use of undefined constant JSON_THROW_ON_ERROR - assumed 'JSON_THROW_ON_ERROR' (this will throw an Error in a future version of PHP) in /data/www/MOODLESITE/public_html/enrol/attributes/edit.php on line 112

Warning: json_decode() expects parameter 4 to be integer, string given in /data/www/MOODLESITE/public_html/enrol/attributes/edit.php on line 112

Notice: Undefined property: stdClass::$groupselect in /data/www/MOODLESITEpublic_html/enrol/attributes/edit.php on line 113

Warning: Use of undefined constant JSON_THROW_ON_ERROR - assumed 'JSON_THROW_ON_ERROR' (this will throw an Error in a future version of PHP) in /data/www/MOODLESITE/public_html/enrol/attributes/edit.php on line 114

Warning: json_encode() expects parameter 2 to be integer, string given in /data/www/MOODLESITE/public_html/enrol/attributes/edit.php on line 114

**Debug information when going back to settings**
customtext1=
line 132 of /enrol/attributes/edit.php: call to debugging()

Notice: Trying to get property 'rules' of non-object in /data/www/MOODLESITE/public_html/enrol/attributes/lib.php on line 282
fieldsandrules= Array ( [customuserfields] => Array ( [7] => thema [11] => dealer_code [13] => dealer_code_sub [39] => region_ce [41] => region_nonce [43] => cb_mit [45] => cb_cat [47] => cb_uni [49] => cb_TCM [51] => cb_MLE [53] => rol_manager [55] => rol_student [61] => sales_level_1 [63] => sales_level_2 [65] => technical_level_1 [67] => technical_level_2 [69] => mle_employee_level_1 [71] => mle_employee_level_2 [73] => mle_office_employee_level_1 [75] => mle_office_employee_level_2 [79] => hq [81] => cb_nic ) [rules] => )
line 134 of /enrol/attributes/edit.php: call to debugging()

Warning: Invalid argument supplied for foreach() in /data/www/MOODLESITE/public_html/enrol/attributes/lib.php on line 301
arraysql= Array ( [select] => [where] => 0 [params] => Array ( ) )
line 136 of /enrol/attributes/edit.php: call to debugging()
sqlquery= SELECT DISTINCT u.id FROM {user} u WHERE 0
line 139 of /enrol/attributes/edit.php: call to debugging()
countusers= 0
line 141 of /enrol/attributes/edit.php: call to debugging()

**Comment by ndunand** [comment]
Hi @gemguardian ,

Thanks for reporting and providing all relevant information. I think the problems stems from the first warning:

```
Warning: Use of undefined constant JSON_THROW_ON_ERROR [...]
```

This is most likely due to the fact that you are using a version of PHP lower than 7.3.0, as indicated in https://www.php.net/manual/en/class.jsonexception.php .

This is not to be advised as PHP versions < 7.3 have been unsupported (even just for security fixes) for about a year. You should use at least PHP 7.4, which is currently supported.

**Comment by gemguardian** [comment]
Hi
Thank you for your fast response. Just checked the learning enviroments PHP information, and you are correct - they run on PHP7.2. 
I will send a mail to the support desk of the hostingparty. 
Gem

**Comment by gemguardian** [comment]
Hi @ndunand 

I can confirm that update the PHP version solve this issue. 

I do have one remark though. 

On Moodle.org it is noted that this version supports 3.5 to 3.11 - and (even though not recommened) there will be many that still use PHP7.2 in Moodle versions up to 3.10 - can I recommend you that you would add a note in the release note that this version recuires at least PHP 7.3 ?

**Comment by ndunand** [comment]
Hi @gemguardian 

Thanks for reporting back.

I did add the PHP version info you requested to the current version information, but can't be sure I'll remember to do it for each release. In any case, running an obsolete stack will most likely break other things in the long run.
