### ISSUE TITLE
Not updating the information or enrolling users in the course

### ISSUE THREAD

**Issue by htuspeaking** [ndunand/moodle-enrol_attributes#46]
Hi, 

I'm trying to enroll users automatically using this plugin but for some reason, once the users are created with all the information needed in their profile, they are not enrolled automatically in the course that meets that information. 

To be clear, one of the information that users are asked for when creating their account is the language they want to learn. That's the field we are using then so they can be enrolled in the course, but when we check, the user is not enrolled in any course. 

Can someone help us, please?

**Comment by mgleeson** [comment]
Hi there,   
  
If you click the "Force enrolments now" button in the edit page of one of the enrolment method instances you have already setup, does that appear to trigger the enrolment(s) as would have otherwise been expected for that course?

**Comment by mgleeson** [comment]
If "Force enrolments now" indeed works, this issue may potentially be related to #48

**Comment by NicoAlexH** [comment]
Just fixed #48, closing this issue for now.
