### ISSUE TITLE
Customint1 field incorrectly set when creating new enro_attributes method

### ISSUE THREAD

**Issue by jrm-unamur** [ndunand/moodle-enrol_attributes#55]
When creating a new enrol_attributes method, the "customint1" field is always set to 1 (unenrol user) because the code only checks that this field is set and doesn't check its value
`'customint1'  => isset($data->customint1)` (edit.php line 96)
while when editing an existing method this field is properly set
$instance->customint1 = isset($data->customint1) ? ($data->customint1) : 0; (edit.php line 85)

Regards

Jean-Roch

**Comment by NicoAlexH** [comment]
Fixed by #56, thank you for reporting this issue !
