### ISSUE TITLE
Get 404 error

### ISSUE THREAD

**Issue by juancrrn** [ndunand/moodle-enrol_attributes#6]
When I try to add "Enrol by user profile fields" enrolement method it redirects to mydomain/moodle/enrol/attributes/edit.php?courseid=X. I have WordPress installed in my main directory and it returns a "404 error: page not found". Accessing through FTP the folder and the files are there... What am I doing wrong?

**Comment by ndunand** [comment]
It is possible the WordPress could have an impact on this. Try to temporarily remove the `.htaccess` file at the root of the WordPress installation to see whether it resolves the issue.

**Comment by juancrrn** [comment]
Then, if I remove the .htaccess file, it returns a 500 error: internal server error. Does the plugin require any special requirements or permissions?
El 1/12/2015 7:43, Nicolas Dunand notifications@github.com escribió:It is possible the WordPress could have an impact on this. Try to temporarily remove the .htaccess file at the root of the WordPress installation to see whether it resolves the issue.

**Comment by juancrrn** [comment]
I need to find a solution soon because it's a very important project for my school. Please help me :)

**Comment by ndunand** [comment]
Is the 404 error displayed with Moodle's branding, or is it a generic 404 page?

Also, does the page `mydomain/moodle/course/view.php?courseid=X` display properly?

**Comment by juancrrn** [comment]
As I said, if I remove the .htaccess file in the main directory, it shows a 500 Internal Server error (generic page). If I don't remove it, WordPress displays a 404 Not Found error.
And no, it displays correctly if it's 'mydomain/moodle/course/view.php?id=X' (not 'view.php?courseid=X').
Thanks for your help!
On Jan 6, 2016 10:21 AM, Nicolas Dunand notifications@github.com wrote:Is the 404 error displayed with Moodle's branding, or is it a generic 404 page?

Also, does the page mydomain/moodle/course/view.php?courseid=X display properly?

**Comment by ndunand** [comment]
Moodle should work without any issues when not using `.htaccess` files. If removing the file breaks your Moodle, then there is the problem.

**Comment by juancrrn** [comment]
With the .htaccess there, if I go to the plugin it shows a 404 page the first time. If I reloas the page, then it shows a 500 page, so I don't think it's a problem with that file. Does the plugin need access to 'view.php?courseid=X'? I can't access that page and that could be the problem...
On Jan 6, 2016 3:58 PM, Nicolas Dunand notifications@github.com wrote:Moodle should work without any issues when not using .htaccess files. If removing the file breaks your Moodle, then there is the problem.

**Comment by ndunand** [comment]
No, the plugin does not need access to any other files normally.

**Comment by juancrrn** [comment]
If you want to help us (we're a team) we could give you access to the website.

**Comment by juancrrn** [comment]
I've installed another enrol plugin and it doesn't work neither, so it has to be a problem in my Moodle installation. I'm going to re-install the whole site to see if it works...

**Comment by ndunand** [comment]
Hi, thanks for reporting back. Let me know.

**Comment by juancrrn** [comment]
Solved, it was a problem with permissions (I didn't remember that directories have to have 755 permission and files 644). Thanks to Neolo.com for their help!

**Comment by ndunand** [comment]
Well I wouldn't have thought of that. Thanks for reporting back.
