### ISSUE TITLE
Additional comparison operators, instead of "equals"

### ISSUE THREAD

**Issue by Kigh** [ndunand/moodle-enrol_attributes#8]
Hi,
Is it possible to add an other string comparison, instead of only an equals? For example an "like". Currently i can't whitelist multiple users with same domainnames in their email attribute fields. (i.e. usera@test.com, userb@test.net, userc@test.xyz). I would like to have "@test." compared to the email attribute field.

Or alternatively enable RegEx in the field, so my example from above would then be "_@test._".

As an short term solution, i would be happy to customize, if you could point me to the PHP code line?

Thanks!

**Comment by ndunand** [comment]
Hi,

Good idea! The relevant code is here: [lib.php#L163](https://github.com/ndunand/moodle-enrol_attributes/blob/master/lib.php#L163)

**Comment by Kigh** [comment]
Hi thanks for pointing me to the line! It looks already so, that the check there is not only checking the whole string. The "%" in the SQL statement will also make a partial check?!
You have a
- equals value
- equals \* value
- equals value *
- and an equals \* value *
  or am i mistaking? So it already works?

**Comment by ndunand** [comment]
Hi,

Well, it looks for semicolon-separated values. So if a profile field `x` contains the string `"a;b;c"`, then this would trigger any rule like `x=a`, `x=b`, `x=c`.

**Comment by Kigh** [comment]
Thanks again. I simply copied the last OR and removed the `;`The following additional OR rule should do the trick, right?
Before:

```
OR  d'.$join_id.'.data LIKE \'%;'.$rule->value.';%\' 
```

After:

```
OR  d'.$join_id.'.data LIKE \'%;'.$rule->value.';%\' 
OR  d'.$join_id.'.data LIKE \'%'.$rule->value.'%\' 
```

I know that this will have sideeffects and shouldn't be used w/o any additional config + logic in your plugin. In our case it will be save, because it's internal only and it's ensured that the mailadress i'm going to use always contains the same domain. Nevertheless this would benefit a lot of other projects as well i believe...

**Comment by ndunand** [comment]
Yes, that would work. You have to be carfeul though, as

```
LIKE '%n.smith@example.org%'
```

would match `n.smith@example.org`, but also `john.smith@example.org` and `nathan.smith@example.org`.

If you're fine with that (and other side effects) then you're good to go I guess.

In the future, I might want to add RegEx support in the plugin.

**Comment by Kigh** [comment]
Fair warning, thanks. In my case that doesn't matter. All employees have the mail attribute maintained in AD with the following structure `<name>@company.<TLD>`. I simply can copy this into a moodle-custom-user-field (protected + invisible for users) via the standard LDAP Auth. Plugin.

Then using you plugin with the customization above, i can simply type in `@company.` and make sure all LDAP logged in employees can enroll in the appropriate courses.

In all other solutions I've looked into, I'd have to change something in the AD...

**Comment by ndunand** [comment]
Right, that looks fine to me indeed.

**Comment by fwsl** [comment]
Would it work with multivalued fields?
Example:
I have custom field called `groups` which contains all groups user belongs to, lets say "`group1 group2`" etc.
In a course I'd like to enroll all users from `group1`. Currently it's impossible, or am I wrong?

Second thing. If this would work, nice thing would be the possibility to exclude groups. 
`custom_field =/= value` (or `*value*` in multivalued field)
or possibility to add `NOT` just like `AND` and `OR`

**Comment by Kigh** [comment]
This would need definitely more customizing than my case (which is very limited). Nevertheless, also a reasonable request.

**Comment by fwsl** [comment]
I think this would also work in Your case, You could use _value_ to match any part of the email.

**Comment by Kigh** [comment]
But in my case it's guaranteed that there is only one value, which is the mail. @ndunand mentioned some sideeffects with my customization/hack, which would potentially mess up your "group1 group2" use case. For example, if a groupnameA consist partly of groupnameB, there can be problems...

**Comment by fwsl** [comment]
I'm aware of this, but this could also be an advantage. You could have groups saved like this `group.year.faculty`  and could match users with any combination of those three properties.

@ndunand what do You think about such enhancement 

P.S. I need to stop speed reading, I think most of my cases could be solved by just changing spaces to `;`  between groups. 

@ndunand BTW I've added Polish translation on lang.moodle.org not sure if You get updates about this things, so I'm letting You know.

**Comment by ndunand** [comment]
Thanks for the translation, I hadn't seen it.

And yes you're right about using semicolons.

**Comment by NicoAlexH** [comment]
Added new comparison operators : https://github.com/ndunand/moodle-enrol_attributes/pull/52
