### ISSUE TITLE
Enrolment method not displaying

### ISSUE THREAD

**Issue by CamBanfield** [ndunand/moodle-enrol_attributes#9]
Hi,

The plugin has been installed and enabled under the "Manage enrol plugins" section in Moodle however it fails to display in the course enrolment selection page within "Add method" dropdown box. I'm also unable to locate any errors relating to the plugin.

Moodle version: 2.9.3 (20151109)
Plugin version: 2.1 for Moodle 2.7-3.0 (build 2015111700)

If you would like more information or want me to test anything just let me know!

Thanks

**Comment by ndunand** [comment]
Hi,

Can you check the plugin's configuration? At least one custom profile field has to be selected in the main config for the plugin to allow creation of instances.

**Comment by CamBanfield** [comment]
Hi,

Oops! Sorry about that, I didn't have the custom profile field selected (was trying to use the "Department" field instead of a fresh custom one). As soon as I added a new custom field it worked perfectly, derp!

Thanks again I'll close this now :)

**Comment by ndunand** [comment]
Alright, good! Thanks for reporting back
